### ISSUE TITLE
Client Crash upon logging into server 

### ISSUE THREAD

**Issue by Judgess999** [p455w0rd/DankNull#134]
I have had the same issue on my server this weekend and week.
"Crash upon logging into server #99"

Direwolf20 1.12 pack
I put some XNet cable in my Dank/Null and on entry it crashed the game.

Time: 9/4/18 10:05 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
at p455w0rd.danknull.client.render.DankNullRenderer.renderItem(DankNullRenderer.java:107)
at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:149)
at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:213)
at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1160)
at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:547)
at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at p455w0rd.danknull.client.render.DankNullRenderer.renderItem(DankNullRenderer.java:107)
at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:149)

-- Item being rendered --
Details:
Item Type: p455w0rd.danknull.items.ItemDankNull@6ea658df
Item Aux: 3
Item NBT: {danknull-inventory:[{Slot:0,id:"minecraft:sandstone",Count:0b,Damage:0s,RealCount:2048},{Slot:1,id:"minecraft:stone",Count:-119b,Damage:5s,RealCount:1417},{Slot:2,id:"minecraft:stone",Count:0b,Damage:3s,RealCount:2048},{Slot:3,id:"chisel:marble2",Count:-122b,Damage:7s,RealCount:1670},{Slot:4,id:"minecraft:stained_hardened_clay",Count:33b,Damage:8s,RealCount:33},{Slot:5,id:"minecraft:cobblestone",Count:-10b,Damage:0s,RealCount:2038},{Slot:6,id:"chisel:basalt2",Count:-32b,Damage:7s,RealCount:1504},{Slot:7,id:"minecraft:stone",Count:-116b,Damage:1s,RealCount:1676},{Slot:8,id:"chisel:limestone2",Count:-51b,Damage:7s,RealCount:461},{Slot:9,id:"minecraft:stone",Count:31b,Damage:0s,RealCount:1311},{Slot:10,id:"minecraft:obsidian",Count:99b,Damage:0s,RealCount:355},{Slot:11,id:"minecraft:netherrack",Count:0b,Damage:0s,RealCount:2048},{Slot:12,id:"minecraft:gravel",Count:0b,Damage:0s,RealCount:2048},{Slot:13,id:"minecraft:sand",Count:-13b,Damage:0s,RealCount:1267},{Slot:14,id:"minecraft:nether_brick",Count:-40b,Damage:0s,RealCount:216},{Slot:15,id:"minecraft:soul_sand",Count:-2b,Damage:0s,RealCount:1022},{Slot:16,id:"minecraft:glass",Count:-13b,Damage:0s,RealCount:243},{Slot:17,id:"extrautils2:decorativeglass",Count:42b,Damage:4s,RealCount:42},{Slot:18,id:"minecraft:dirt",Count:121b,Damage:0s,RealCount:633},{Slot:19,id:"xnet:advanced_connector",Count:62b,Damage:0s,RealCount:62},{Slot:20,id:"xnet:netcable",Count:82b,Damage:0s,RealCount:82}],ExtractionModes:[{Mode:1,Stack:{id:"minecraft:stone",Count:1b,tag:{ExtractionMode:1},Damage:0s}},{Mode:0,Stack:{id:"minecraft:cobblestone",Count:1b,tag:{ExtractionMode:0},Damage:0s}},{Mode:1,Stack:{id:"minecraft:dirt",Count:1b,tag:{ExtractionMode:1},Damage:0s}}],selectedIndex:19}
Item Foil: true
Stacktrace:
at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:213)
at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1160)
at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:547)
at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)

**Comment by p455w0rd** [comment]
shouldnt be an issue..let me know if it still is..I will be removing the CCL dependency in the next update, so the rendering code is getting an overhaul..I would like to know if this is still an issue in the latest version tho

**Comment by kreezxil** [comment]
I think this is related, I had player put some non-placeable items in his dank/null and he couldn't get one either until I removed the dank/null from his hotbar via NTBexplorer.


[4a902fe5-c6dd-43c3-839b-b27884e538dc.zip](https://github.com/p455w0rd/DankNull/files/2438488/4a902fe5-c6dd-43c3-839b-b27884e538dc.zip)

**Comment by TheAmazingHaru** [comment]
i was using the denk null as a storage chest my player data above
 Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at p455w0rd.danknull.client.render.DankNullRenderer.renderItem(DankNullRenderer.java:107)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at codechicken.lib.render.item.CCRenderItem.func_184394_a(CCRenderItem.java:240)
	at codechicken.lib.render.item.CCRenderItem.func_184392_a(CCRenderItem.java:302)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:75)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:432)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:333)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:776)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1439)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at p455w0rd.danknull.client.render.DankNullRenderer.renderItem(DankNullRenderer.java:107)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at codechicken.lib.render.item.CCRenderItem.func_184394_a(CCRenderItem.java:240)
	at codechicken.lib.render.item.CCRenderItem.func_184392_a(CCRenderItem.java:302)
	at net.minecraft.client.renderer.ItemRenderer.func_187462_a(ItemRenderer.java:75)
	at net.minecraft.client.renderer.ItemRenderer.func_187457_a(ItemRenderer.java:432)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:333)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:776)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1439)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

Edit: i should probably yell at the StoneBlock Modpack guy for not having DankNull updated

**Comment by p455w0rd** [comment]
are you using an old version? line 107 (what this is referencing) no longer contains executable code..please update to latest if you haven't and tell me if this still exists - https://minecraft.curseforge.com/projects/dank-null/files/2622880
also paste full logs (so I can tell what version you're using) using a service like pastebin or github gist and paste a link to said log here when posting logs

**Comment by kreezxil** [comment]
We're using the new StoneBlock modpack,... guess we'll have to report this
to the mod pack dev now. thanks. :)

**Comment by kreezxil** [comment]
@p455w0rd good call on that Stoneblock is running old code. 

![screenshot_1](https://user-images.githubusercontent.com/3880072/46408257-27097680-c6d7-11e8-9212-302592069e30.png)
