### ISSUE TITLE
Works in SP not in MP, have same files

### ISSUE THREAD

**Issue by joeafro** [p455w0rd/DankNull#218]
when was looking at the latest log i found this

[03:15:51] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: p455w0rd.danknull.api.IDankNullHandler.isItemValid(ILnet/minecraft/item/ItemStack;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: p455w0rd.danknull.api.IDankNullHandler.isItemValid(ILnet/minecraft/item/ItemStack;)Z
	at p455w0rd.danknull.container.ContainerDankNull.addStack(ContainerDankNull.java:184) ~[ContainerDankNull.class:?]
	at p455w0rd.danknull.container.ContainerDankNull.func_82846_b(ContainerDankNull.java:160) ~[ContainerDankNull.class:?]
	at p455w0rd.danknull.container.ContainerDankNull.func_184996_a(ContainerDankNull.java:105) ~[ContainerDankNull.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

it happens each time i attempt to put an item into the dank/null/

**Comment by BrockWS** [comment]
What version of Forge and DankNull are you using?

**Comment by joeafro** [comment]
forge 14.23.5.2847
DankNull  1.6.80
we are playing minecraft 1.12.2

**Comment by Morpheus1101** [comment]
I just tested this in a SMP enviroment and it works perfectly fine placing an item into any version of the dank/null.  Did you download the mod from curseforge? And what item specifically r u trying to place in when the crash occured?


![2019-10-12_19 57 53](https://user-images.githubusercontent.com/10524952/66699490-b570f900-ed2a-11e9-8b96-4b7c26e426d6.png)

**Comment by joeafro** [comment]
i said in title works in single player, not on my server, and the dank null isn't accepting any items into its inventory

**Comment by Morpheus1101** [comment]
I cant reproduce your issue myself as i am able to get it working perfectly fine on Multiplayer on a server

**Comment by BrockWS** [comment]
Can you verify that the server is running the same forge version? Could you also provide the full mod list including each version?
