### ISSUE TITLE
Not compatable with imersive engieering

### ISSUE THREAD

**Issue by Pultex** [p455w0rd/DankNull#235]
all versions past 
DankNull-1.12.2-1.6.80
and
p455w0rdslib-1.12.2-2.2.156

shader error with

Immersive Engineering 0.12 - 92

shows:
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.NoSuchMethodError: p455w0rdslib.proxy.CommonProxy.areShadersEnabled()Z
	at p455w0rd.ae2wtlib.init.LibApiImpl$WTConfigImpl.areShadersEnabled(LibApiImpl.java:554)
	at p455w0rd.ae2wtlib.init.LibEvents.attachCapabilities(LibEvents.java:70)

**Comment by p455w0rd** [comment]
update ae2wtlib/wireless terminal mods

**Comment by Pultex** [comment]
sorry did not know it was part of the modpack

thank you for posting back
