### ISSUE TITLE
Stacktrace on logging in concurrent.ExecutionException

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/DankNull#251]
Using TownCraft 4.2 - I have this in my client log when logging in to my server.
DankNull-1.12.2-1.7.89

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at p455w0rd.danknull.network.PacketConfigSync$Handler.handle(PacketConfigSync.java:79) ~[PacketConfigSync$Handler.class:?]
	at p455w0rd.danknull.network.PacketConfigSync$Handler.lambda$onMessage$0(PacketConfigSync.java:69) ~[PacketConfigSync$Handler.class:?]
	at p455w0rd.danknull.network.PacketConfigSync$Handler$$Lambda$2985/1692909954.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 9 more
```

Entire log-
[latest.log](https://github.com/p455w0rd/DankNull/files/4022040/latest.log)

**Comment by NicMoore88** [comment]
Seconded.  Nearly identical error in MCEternal modpack.
Dank/null-1.12.2-1.7.89

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at p455w0rd.danknull.network.PacketConfigSync$Handler.handle(PacketConfigSync.java:79)
    at p455w0rd.danknull.network.PacketConfigSync$Handler.lambda$onMessage$0(PacketConfigSync.java:69)
    at p455w0rd.danknull.network.PacketConfigSync$Handler$$Lambda$7233/375401435.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
```
Latest Log:
[crash-2020-01-08_21.42.49-client.txt](https://github.com/p455w0rd/DankNull/files/4038512/crash-2020-01-08_21.42.49-client.txt)

**Comment by NicMoore88** [comment]
After a quick test...and this seems strange to me, but I'm no developer....

The first crash happened upon switching my GUI size to "Normal".  Immediate desktop crash.
Reloaded game, logged into server, still on Normal GUI size, crash on load.
Reloaded game, switched to Large GUI size. Loaded in just fine, no issues since.

**Comment by ghost** [comment]
Thirded 1.12.2-1.7.89, Also MC.Eternal

[crash-2020-03-05_12.52.24-client.txt](https://github.com/p455w0rd/DankNull/files/4294382/crash-2020-03-05_12.52.24-client.txt)

**Comment by Recaran** [comment]
Foruth..ed? 

Getting this happen to a player on my server when opening the book of shadows from Bewitchment. Exactly the same error as everyone else, on MC Eternal 1.3.4.

**Comment by TigerWalts** [comment]
I've looked at some the config sync messaging code and the Null Pointer Exception is happening when trying to read in the **DisableOreDictMode** from the message.

All the other settings read in OK and the only difference I can spot is that the **DisableOreDictMode** setting is the only Boolean setting that it is trying to read in.

I suspect that Boolean config values are not making it through the messaging correctly. The message stores the values in a Map<String, Object> but I don't think the boolean type is an object and so may not be getting stored correctly.

**Comment by cjm721** [comment]
Duplicate #237
