### ISSUE TITLE
A /dank/null docking station stalls our server

### ISSUE THREAD

**Issue by Yarillo4** [p455w0rd/DankNull#266]
Version: 
* DankNull-1.12.2-1.7.89
* p455w0rdslib-1.12.2-2.3.161

Thanks for your time :)

```
Stall report from 2020-03-28 23:45:00 +0000, 76 threads, stalled for at least 30000 ms.
Thread dump #1 for stall #1.
Heap memory usage: 5583 / 9344 MB (max. 12784 MB).
Created by sampler 1.84 (MC 1.12).

"Server thread" #22 prio=5
RUNNABLE
	at java.util.HashMap.putVal(HashMap.java:629)
	at java.util.HashMap.put(HashMap.java:612)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.item.ItemStack.func_77955_b(ItemStack.java:228)
	at net.minecraft.item.ItemStack.serializeNBT(ItemStack.java:1184)
	at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1.lambda$writeNBT$0(CapabilityDankNull.java:46)
	at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1$$Lambda$5088/43755459.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1.writeNBT(CapabilityDankNull.java:43)
	at p455w0rd.danknull.inventory.cap.CapabilityDankNull$1.writeNBT(CapabilityDankNull.java:26)
	at net.minecraftforge.common.capabilities.Capability.writeNBT(Capability.java:112)
	at p455w0rd.danknull.blocks.tiles.TileDankNullDock.func_189515_b(TileDankNullDock.java:209)
	at p455w0rd.danknull.blocks.tiles.TileDankNullDock.func_189517_E_(TileDankNullDock.java:165)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Yarillo4** [comment]
I've noticed #256 just about now, I'm not sure if it's related since the stack trace is apparently not very similar

**Comment by cjm721** [comment]
Would update to version 90 (which is pushing to curse currently). If still exists in 90 create a new issue.
