### ISSUE TITLE
Placing blocks issue

### ISSUE THREAD

**Issue by DrakusorU** [p455w0rd/DankNull#42]
I got a problem after the last update, but only to my main modpack ( 180+ mods ).. I tried with a new instance and I have no issues.. I dunno how to debug this so maybe you could help me.. But everytime I try to place a block using the danknull, it places an 'invisible' block and I have to place a second block in the same spot for it to actually render.. also after the first 'block place' even though the block isn't render, its still kinda there, I get this weird glitch like I get stuck in cobweb but can't move at all through that block..
I downgraded to 1.0.14 and I have no issues anymore.. but with a new instance and with the lastest version I have no issues as well.. so.. it could be a mod conflict? I don't really know how can I debug this as I don't get any crash..

**Comment by Morpheus1101** [comment]
Can confirm with limited mods that this does in fact occur, but im unable to place any blocks in that position.  If i do a /fill with air the issue re-occurs when trying to place another block down.  Exiting tthe game and re-joining allows a block to then be placed normally in that spot using /dank/null

**Comment by p455w0rd** [comment]
For me, in SMP with JEI, CCL, WAILA, TOP, SwingThroughGrass, and p455w0rdsLib, it works correctly. So I'm guessing mod interaction. Will look into it and try to figure it out.

**Comment by DrakusorU** [comment]
`[02:48:38] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$PlaceEvent@760168ad:
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_25]
	at com.feed_the_beast.ftbl.api_impl.Universe.getPlayer(Universe.java:118) ~[Universe.class:?]
	at com.feed_the_beast.ftbl.api_impl.Universe.getPlayer(Universe.java:27) ~[Universe.class:?]
	at com.feed_the_beast.ftbu.api_impl.ClaimedChunks.canPlayerInteract(ClaimedChunks.java:420) ~[ClaimedChunks.class:?]
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockPlace(FTBUPlayerEventHandler.java:137) ~[FTBUPlayerEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_FTBUPlayerEventHandler_onBlockPlace_PlaceEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:149) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:883) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) [aip.class:?]
	at p455w0rd.danknull.items.ItemDankNull.func_180614_a(ItemDankNull.java:308) [ItemDankNull.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:852) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) [aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]`

checked the log right after I tried placing a block, this is what I get in the log

**Comment by p455w0rd** [comment]
ohhhh...that does make sense! hmm...I'll have to do some integration to auto-add my fake player when chunks are claimed...I can see why not wanting a fake player to be able to place a block would be desired..say you have an autonomous activator precisely on the edge (outside) of a claimed chunk, but facing into the chunk..the autonomous activator could then, for instance, place TNT, and then ignite it...so I'll have to special case FTB Utils and figure out a way to auto-add each player's /dank/null fake player clone to the team or something...i've heard FTB Utils actually has a config to disable its ability to disable placing of blocks by Fake Players, but my Fake Player is custom (it'd not a standard Fake Player), and MC actually sees it as another real player..I have to think on this, but i'll figure something out and get it fixed...as for @Morpheus1101 ...his mod list didn't include FTBUtils, so I'm stumped on that one unless CoFH Core does some kind of blocking as well...at any rate, Thank You @DrakusorU !

**Comment by DrakusorU** [comment]
I have CoFH core, world, thermal expansion on both intances, as long as I try placing a block somewhere where chunks are not claimed by FTBUtilities I have no issues, so I don't think there is a conflict between those mods unless they are some options those mods add that I don't use or I don't know about them..

**Comment by p455w0rd** [comment]
I'm going to close this as #44 resolves these issues :)
