### ISSUE TITLE
Crash on opening diamond dank/null

### ISSUE THREAD

**Issue by loudwhitenoise** [p455w0rd/DankNull#51]
I shift-r-clicked to open it up and boom, CTD. I don't know if this happens with the other sizes of the dank/null, because it was my first one.

 Forge .2575, Minecraft 1.12.2

`[11:16:54] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 295, Size: 4
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_121]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
	at p455w0rd.danknull.client.gui.GuiDankNull.func_73863_a(GuiDankNull.java:175) ~[GuiDankNull.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:366) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 17 more`

**Comment by p455w0rd** [comment]
thanks for this...will be fixed in coming update
